global:
  # /metrics executes live GraphQL queries and can be slow.
  scrape_interval: 30m
  scrape_timeout: 120s
  evaluation_interval: 30m

scrape_configs:
  - job_name: tfgql
    metrics_path: /metrics
    scheme: http
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/secrets/tfgql.token
    static_configs:
      - targets:
          - tfgql:4000
